using KUnet
@date include("testdense.jl")
@date include("testsparse.jl")
@date include("testconvert.jl")
@date include("testlinalg.jl")
@date include("testperceptron.jl")
# @date include("testkperceptron.jl")
@date include("testlayers.jl")
@date include("testmnist.jl")
# @date include("tutorial.jl")
