include("header.jl")
# @time include("core.jl")
@time include("primitive.jl")
@time include("nonlinear.jl")
@time include("cnn.jl")
@time include("rnn.jl")
@time include("loss.jl")
@time include("special.jl")
# @time include("data.jl")
